title: HackingUtils.c blog
description: Blog comnitario de HackingUtils.c
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
collections:
  articles:
    output: true
    permalink: /links/:path/
baseurl: /hu-blog
url: https://essenemigz.github.io